services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/home/admin/app
    networks:
      - selenium_network

  #db:
  #  image: postgis/postgis:15-3.3
  #  ports:
  #    - 5432:5432
  #  environment:
  #    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #    - POSTGRES_DB=${POSTGRES_DB}
  #    - POSTGRES_USER=${POSTGRES_USER}
  #  volumes:
  #    - pgdata:/var/lib/postgresql/data
  #  networks:
  #    - selenium_network

  selenium:
    image: selenium/standalone-chrome:4.26.0
    ports:
      - "4444:4444"
    environment:
      - SE_EVENT_BUS_HOST=selenium
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - OTEL_EXPORTER_DISABLED=true
      - SE_ENABLE_TRACING=false
    networks:
      - selenium_network

  #pgadmin:
  #  image: dpage/pgadmin4:8.11.0
  #  ports:
  #    - 5050:80
  #  environment:
  #    - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
  #    - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  #  networks:
  #    - selenium_network

  chrome:
    image: selenium/node-chrome:4.26.0
    depends_on:
      - selenium
    environment:
      - SE_EVENT_BUS_HOST=selenium
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - HUB_HOST=selenium
      - NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5

#volumes:
#  pgdata:

networks:
  selenium_network:
    driver: bridge
